### ISSUE TITLE
Clarification on animation frame task

### ISSUE THREAD

**Issue by Johanna-hub** [w3c/screen-orientation#136] opened 2019-01-22 11:49 UTC
Currently in the spec we have:

>  <p>
>         The following is used but not defined in [[FULLSCREEN]]: <dfn><a href=
>         'https://github.com/whatwg/fullscreen/issues/16'>animation frame
>         task</a></dfn>.
>       </p>

According to the fullscreen issue referenced above the timing is now defined and the issue has been closed.

@foolip Would you please be able to clarify what this means for the definition in the Screen Orientation spec and also where animation frame task appears in the algorithms:

>   <p>If locking the orientation did not result in a change of
>           orientation, as part of the next <a>animation frame task</a>, resolve
>           <var>pending-promise</var> with <code>undefined</code> and set <var>
>             pending-promise</var> to <code>null</code>.
>           </p>        

> <p>
>           Whenever the viewport's angle changes, the <a>user agent</a> MUST run
>           the following steps as part of the next <a>animation frame task</a>:
>         </p>

> <p>
>           Whenever a <a>document</a> becomes visible per [[!PAGE-VISIBILITY]],
>           in other words after the <a>now visible algorithm</a> is run, the
>           <a>user agent</a> MUST run the following substeps as part of the next
>           <a>animation frame task</a>:
>         </p>

Thank you very much for your help 🙂

**Comment by marcoscaceres** [comment] 2019-01-23 15:22
Potential duplicate of https://github.com/w3c/screen-orientation/issues/97

**Comment by foolip** [comment] 2019-01-24 13:46
The way to integrate with the event loop that we ultimately landed on is https://fullscreen.spec.whatwg.org/#run-the-fullscreen-steps. There is a step in https://html.spec.whatwg.org/multipage/webappapis.html#update-the-rendering that calls out to HTML.

This does mean that HTML needs to know about all the specs that integrate with it, which is arguably backwards layering-wise, but the upside is that the order of things is clearly defined, and cannot really be well defined without a central point of order.

**Comment by Johanna-hub** [comment] 2019-01-29 12:59
@foolip Thanks so much

**Comment by marcoscaceres** [comment] 2022-10-25 04:30
Closing as duplicate of #219

**Closed as completed by marcoscaceres** 2022-10-25 04:30 UTC
Labels: cross-doc
